on:
  push:
    branches:
      - develop
      - master

name: Test and Checks

jobs:
  build:
    name: Test and Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Elixir
      uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.2.6
        elixir-version: 1.10.1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Setup Components
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile
        npm install --prefix assets
        git config --global user.email "mail@insprac.io"
        git config --global user.name "insprac"

    - name: Test
      run: mix test
      env:
        ERGO_TEST_WEB_HOST: localhost
        ERGO_TEST_WEB_PORT: 4002
        ERGO_TEST_WEB_SECRET_KEY_BASE: "ieY8HWj3z69gMG6AwrJtL4dtE865jBi4sj4QW8hmuB4KZAUREunBdH7UVCNfARt8"
        ERGO_TEST_WEB_LIVE_VIEW_SIGNING_SALT: "abc123"

    - name: Dialyzer
      run: mix dialyzer
